### PR TITLE
Fixed Buffer construction issues on Node v4

### LINKED ISSUE #1102: Error: this is not a typed array
[This change is introduced in version 6](https://github.com/postmanlabs/newman/commit/f86a9efb92ef92dcb058fe93995861452f25c1d5)

Please refer [this](https://nodejs.org/api/buffer.html#buffer_buffer)

Hence need to upgrade node version in package.json

### PR DESCRIPTION
**Pull request by kunagpal**
Resolves #1102, closes #1103

### CODE REVIEW

File: lib/reporters/html/index.js [hunk 1]
```diff
@@ -34,6 +34,8 @@ var fs = require('fs'),
      */
     AGGREGATED_FIELDS = ['item', 'request', 'response'],
 
+    IS_NODE4 = process.version.match(/^v(\d+)\./)[1] === '4',
```
Comment (shamasis) [inline lib/reporters/html/index.js]: This needs protection.

Comment (kunagpal) [inline lib/reporters/html/index.js]: Added protection
