### PR TITLE
Fix CSV Auto Parse

### LINKED ISSUE #1100: Test script passes in Postman but fails in Newman with Numbers in double quotes
newman -3.7.4
-->OS: Windows 10
--> CLI
-->Expected Behaviour: The test should pass in newman with numbers in double quotes. Numbers without quotes in response are working but when numbers are coming in double quotes its not working.

Test Scripts:
var jsonData = JSON.parse(responseBody);
tests["Last4Digit of Car Passed"] = jsonData.vehicles[0].last4VinDigits===data.last; 
console.log(responseBody);

Data File:
plate,cust,manufacturerYear,product,last
AMT210,45156841,1987,FORD,"7747"

Command:
newman -run Testrunner.json -e environment.json -d data.csv
Result:
newman

NewRunner

→ CheckRego
  GET https://api-it1.testservicensw.net/v1/me/registrations/roads/reports/eligibility?plateNumber=AMT210 [200 OK, 967B, 611ms]
  ┌
  │ '{"vehicles":[{"vehicleID":"66027145","vehicleModel":{
  │ "manufacturer":{"code":"FORD","description":"FORD"},"m
  │ anufactureYear":1987,"manufactureMonth":1,"model":{"co
  │ de":"MONDEO","description":"MONDEO"},"bodyShape":{"cod
  │ e":"SED","description":"SEDAN"}},"last4VinDigits":"774
  │ 7","primaryColour":{"code":"20","description":"BLACK"}
  │ ,"plate":{"plateNumber":"AMT210","plateType":"O"}}],"c
  │ ustomer":{"customerName":{"givenName":"SNSW","familyNa
  │ me":"DATA","customerNameText":"Snsw DATA"}},"messages"
  │ :[{"code":"SUCCESS","message":"Success","severity":"SU
  │ CCESS","category":"BUSINESS"}]}'
  └
  √  Body matches vehicleID
  √  Status code is 200
  √  vehicle id value
  √  Plate Number matches
  √  Manufaturer Passed
  1. Last4Digit of Car Passed

┌─────────────────────────┬──────────┬──────────┐
│                         │ executed │   failed │
├─────────────────────────┼──────────┼──────────┤
│              iterations │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│                requests │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│            test-scripts │        1 │        0 │
├─────────────────────────┼──────────┼──────────┤
│      prerequest-scripts │        0 │        0 │
├─────────────────────────┼──────────┼──────────┤
│              assertions │        6 │        1 │
├─────────────────────────┴──────────┴──────────┤
│ total run duration: 751ms                     │
├───────────────────────────────────────────────┤
│ total data received: 326B (approx)            │
├───────────────────────────────────────────────┤
│ average response time: 611ms                  │
└───────────────────────────────────────────────┘

  #  failure           detail                        
                                                     
 1.  AssertionFailure  Last4Digit of Car Passed      
                       at assertion:6 in test-script 
                       inside "CheckRego"

### PR DESCRIPTION
**Pull request by codenirvana**
Fixes #1100 #1215 #1346 

- Add Custom method to parse values
- Use `csv-parse` casting context to avoid parsing values surrounded by quotes
- Update integration tests for CSV parse

### CODE REVIEW

File: lib/run/options.js [hunk 1]
```diff
@@ -110,6 +110,35 @@ var _ = require('lodash'),
...
+     * Custom method to auto parse CSV values
+     *
+     * @private
+     * @param {String} value - CSV field value
+     * @param {Object} context - Context of field value
+     * @param {Boolean} context.quoting - A boolean indicating if the field was surrounded by quotes.
+     * @returns {String|Number|Date}
+     */
+    csvAutoParse = function (value, context) {
+        if (context.quoting) {
```
Comment (kunagpal) [inline lib/run/options.js]: Make the if blocks consistent by returning the processed value directly, this will also let you remove `else` all over.

File: lib/run/options.js [hunk 2]
```diff
@@ -110,6 +110,35 @@ var _ = require('lodash'),
...
     },
 
+    /**
+     * Custom method to auto parse CSV values
+     *
+     * @private
+     * @param {String} value - CSV field value
+     * @param {Object} context - Context of field value
+     * @param {Boolean} context.quoting - A boolean indicating if the field was surrounded by quotes.
+     * @returns {String|Number|Date}
```
Comment (kunagpal) [inline lib/run/options.js]: `Boolean` as well?

File: lib/util.js [hunk 3]
```diff
@@ -172,6 +172,27 @@ util = {
...
             });
+    },
+
+    /**
+     * Helper function to test if a given string is an integer.
+     *
+     * @param {String} value - The string to test for.
+     * @returns {Boolean}
+     */
+    isInt: function (value) {
```
Comment (kunagpal) [inline lib/util.js]: Were these taken from csv-parse? If so, add a comment linking to the original code in this, as well as the function below.

Comment (codenirvana) [reply lib/util.js]: Yes, added the reference in the below function. Will add a proper description.

File: test/integration/comma-test-csv/comma-test-csv.postman_collection.json [hunk 4]
```diff
@@ -16,9 +16,11 @@
             "type": "text/javascript",
             "exec": [
               "var res = JSON.parse(responseBody);",
-              "tests['Stringified number was parsed correctly'] = data.num === 1;",
```
Comment (shamasis) [inline test/integration/comma-test-csv/comma-test-csv.postman_collection.json]: this test was removed @codenirvana ?

Comment (kunagpal) [reply test/integration/comma-test-csv/comma-test-csv.postman_collection.json]: @shamasis It was replaced with an equivalent, as can be seen in the CSV fixture below.
